### ISSUE TITLE
ModuleNotFoundError on Update

### ISSUE THREAD

**Issue by utkonos** [Neo23x0/yarGen#21]
Using a venv from Python 3.7.2 and the following installed via pip:
Successfully installed future-0.17.1 lxml-4.2.5 naiveBayesClassifier-0.1.3 pefile-2018.8.8 scandir-1.9.0

```
$ python yarGen.py --update
Traceback (most recent call last):
  File "yarGen.py", line 26, in <module>
    from naiveBayesClassifier.trainer import Trainer
  File "/Users/user/Downloads/samples/generate/lib/python3.7/site-packages/naiveBayesClassifier/trainer.py", line 1, in <module>
    from naiveBayesClassifier.trainedData import TrainedData
  File "/Users/user/Downloads/samples/generate/lib/python3.7/site-packages/naiveBayesClassifier/trainedData.py", line 1, in <module>
    from ExceptionNotSeen import NotSeen
ModuleNotFoundError: No module named 'ExceptionNotSeen'
```

**Comment by Neo23x0** [comment]
The module `naiveBayesClassifier` isn't usable with Python 3. Please use Python2 instead.
