### ISSUE TITLE
TypeError when creating new goodware strings database

### ISSUE THREAD

**Issue by midav7** [Neo23x0/yarGen#27]
I tried to create new goodware strings database from the directory containing Mach-O samples

```
[+] Creating local database ...
[+] Using './dbs/good-strings-mac_os.db' as filename for newly created strings database
[+] Using './dbs/good-opcodes-mac_os.db' as filename for newly created opcodes database
[+] Using './dbs/good-imphashes-mac_os.db' as filename for newly created opcodes database
[+] Using './dbs/good-exports-mac_os.db' as filename for newly created opcodes database
Traceback (most recent call last):
  File "yarGen.py", line 2288, in <module>
    save(good_json, strings_db)
  File "yarGen.py", line 1870, in save
    file.write(json.dumps(object))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/gzip.py", line 276, in write
    data = memoryview(data)
TypeError: memoryview: a bytes-like object is required, not 'str'
```

**Comment by Neo23x0** [comment]
Fixed in https://github.com/Neo23x0/yarGen/commit/f582ace368175fcbfc079a49178eab8ab88b2b3e
